baseurl = "http://danmol.js.org/"
languageCode = "en-us"
title = "A Dev's Adventures through outer space"
paginate = 5
DisqusShortname = "dan12mol"
Copyright = "All rights reserved - 2015"
theme = "casper"

[params]
	author = "Dan Moldovan"
	description = "A blog where ranting is a day-by-day thing"
	cover = "images/background.jpg"
	bio = "Web Developer - Gamer"
	authorlocation = "Cluj-Napoca, Romania"
	authorwebsite = "http://dan12mol.github.io"
	googleAnalyticsUserID = "UA-66682860-1"
	githubName = "dan12mol"
	twitterName = "lenea92"
	hideHUGOSupport = true
	
[permalinks]
  post = "/:slug/"
